# Generated by Django 5.0.1 on 2026-01-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('accountant', 'Accountant'), ('analyst', 'Analyst')], default='owner', help_text='User role for permissions (owner/accountant/analyst)', max_length=20),
        ),
    ]
